entryPoints:
  web:
    address: :80

experimental:
  plugins:
    bizawayHeaders:
      moduleName: bitbucket.org/bizaway/traefik-header-plugin
      version: v0.1
providers:
  file:
    directory: /etc/traefik/dynamic

log:
  level: DEBUG
